# encoding:utf-8
"""The web-layer seam for the controlled project import (tasks 6.3/6.4).

Why this module exists
----------------------
``GET /api/projects/browse`` is a *read*: the worst a caller can do is learn the
names of directories inside their own root. Importing is a *write* that can copy
an arbitrary server directory into the member's project area, so it needs a
boundary the read path does not have, and it must keep the one the upstream
product already defined for it: a desktop-native selection arrives as an absolute
host path, is only valid on a **loopback** request, and must carry the
**per-start token** the local backend publishes.

This module is that boundary, and it is deliberately separate from
``channel/web/web_channel.py``:

* ``agent/workspace/project_browser.py`` owns *what* a project root is and how a
  directory is copied atomically. It knows nothing about HTTP, sessions or
  handles.
* this module owns *who may ask for what*: loopback, the per-start token, the
  verified database identity (tenant + user), the single-use handle that ties an
  import back to the preview the user actually confirmed, and the quota
  reservation the module is told to make before anything is staged.
* ``web_channel.py`` keeps thin handlers whose signatures stay where the console
  and the upstream merge expect them.

The four conditions a server-path import must satisfy
----------------------------------------------------
1. **Loopback.** ``REMOTE_ADDR`` is a loopback address *and* no forwarding
   header is present, so a reverse proxy cannot make a remote peer look local.
2. **Per-start token.** A value generated by this process and published (mode
   ``0600``) to ``local_import_token_file`` -- or pinned by ``local_import_token``
   for a supervised deployment. Only a client that can read the local filesystem
   can present it, and it does not survive a restart. Comparison is
   constant-time.
3. **Database identity.** The request runs inside the verified request context,
   so the target tenant and owner come from the session, never from the body. An
   import that names another member's session is refused before any path is read.
4. **A single-use handle.** The preview is what the user confirmed; the import
   must present the handle that preview issued, bound to the same member,
   purpose and source, and consumed on first use. A browser that simply posts a
   server path has no handle, and a replayed or re-purposed one is refused.
   Conversely the *upload* transport (a browser that cannot see a server path)
   needs no handle: it names no server path, and the session is the grant.

What it deliberately does not do
--------------------------------
It never reads a path from the request outside the local transport, never widens
allowed source roots from request data, and never re-derives ownership from the
body. The allowed extra source roots come from configuration
(``project_import_source_roots``), because a request may choose *within* a policy
but must not define one.
"""

from __future__ import annotations

import hmac
import json
import os
import secrets
import threading
import time
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

from common.log import logger

__all__ = [
    "ImportSeamError",
    "CODE_LOCAL_PATH_DENIED",
    "CODE_TOKEN_INVALID",
    "CODE_HANDLE_REQUIRED",
    "CODE_HANDLE_INVALID",
    "CODE_CANCELLED",
    "CODE_INVALID_REQUEST",
    "CODE_UPLOAD_TOO_LARGE",
    "PURPOSE_PROJECT_IMPORT",
    "refuse",
    "is_loopback_request",
    "local_import_token",
    "reset_local_import_token",
    "require_local_transport",
    "issue_handle",
    "consume_handle",
    "cancel_handle",
    "is_cancelled",
    "purge_handles",
    "reset_handles",
    "stage_hook",
    "source_roots",
    "read_upload_manifest",
    "preview_upload_request",
    "import_upload_request",
    "reserve_project_slot",
    "record_import_event",
]

# --- refusal codes -----------------------------------------------------------
#
# Stable strings the console branches on and the tests pin. They are produced
# here (the seam decides *why* a request was refused) and rendered by the
# handlers as ``{status: error, code, message}``.

#: The peer is not loopback (or arrived through a proxy): a server-side path may
#: not be named by a remote client.
CODE_LOCAL_PATH_DENIED = "local_path_denied"
#: Loopback, but without the token this process published for local clients.
CODE_TOKEN_INVALID = "token_invalid"
#: A server path was supplied by a client that never confirmed a preview.
CODE_HANDLE_REQUIRED = "handle_required"
#: Unknown, expired, consumed, re-purposed or another member's handle.
CODE_HANDLE_INVALID = "handle_invalid"
#: The user cancelled; nothing was published.
CODE_CANCELLED = "cancelled"
#: Malformed request (missing field, wrong shape, manifest mismatch).
CODE_INVALID_REQUEST = "invalid_request"
#: The uploaded tree exceeds the configured bound.
CODE_UPLOAD_TOO_LARGE = "upload_too_large"

#: The purpose a handle carries. A handle is only ever consumed by the operation
#: that issued it, so one cannot be redeemed for a different effect.
PURPOSE_PROJECT_IMPORT = "project_import"

#: How long an issued handle stays redeemable. Long enough to read a preview and
#: click through a native picker, short enough that an unattended console does
#: not leave import capabilities lying around.
HANDLE_TTL_SECONDS = 600

#: Addresses that mean "this machine". Anything else is a remote client, however
#: the deployment is configured.
_LOOPBACK_ADDRESSES = frozenset({
    "127.0.0.1", "::1", "::ffff:127.0.0.1", "localhost",
})

#: A proxy in front of the app must not turn a remote client into a local one.
_FORWARDED_HEADERS = (
    "HTTP_X_FORWARDED_FOR", "HTTP_X_FORWARDED_HOST", "HTTP_X_FORWARDED_PROTO",
    "HTTP_X_REAL_IP", "HTTP_FORWARDED", "HTTP_CLIENT_IP",
)

#: Default upload bounds. They exist so a browser cannot fill the member's
#: project area (or the server's memory) with one request.
_DEFAULT_MAX_FILE_BYTES = 64 * 1024 * 1024
_DEFAULT_MAX_UPLOAD_BYTES = 512 * 1024 * 1024

#: The per-start token, generated once per process and published for local
#: clients. Keyed so a test (or an embedder rotating its token) can reset it.
_TOKEN_STATE: Dict[str, str] = {}

#: Issued handles, keyed by value. Kept in-process on purpose: the capability is
#: for a client on this machine, and a restart legitimately invalidates it.
_HANDLES: Dict[str, Dict[str, Any]] = {}

#: Serialises the project-slot reservation's count-and-claim, and counts the
#: in-process reservations the filesystem cannot show yet.
_SLOT_LOCK = threading.Lock()
_SLOT_STATE: Dict[str, int] = {"held": 0}


class ImportSeamError(Exception):
    """A refused import request.

    ``code`` is the machine-readable reason the handler renders, ``status`` the
    HTTP status it should answer with. Messages name the offending *input*, never
    a resolved host path, so a refusal cannot be used to probe the filesystem.
    """

    def __init__(self, message: str, *, code: str = "error", status: int = 400):
        super().__init__(message)
        self.code = code
        self.status = status


def refuse(message: str, code: str = CODE_INVALID_REQUEST,
           status: int = 400) -> ImportSeamError:
    """A refusal with the given code/status (never returns)."""
    return ImportSeamError(message, code=code, status=status)


# --- configuration -----------------------------------------------------------


def _conf() -> Mapping[str, Any]:
    """The live configuration, resolved per call so a test can patch it."""
    try:
        from config import conf
        return conf() or {}
    except Exception:  # noqa: BLE001 - an unreadable config has no secrets
        return {}


def _as_path_list(value: Any) -> List[str]:
    """A configuration path list, accepting a list or a separated string."""
    if value is None or value == "":
        return []
    if isinstance(value, (list, tuple)):
        items = [str(item) for item in value]
    else:
        text = str(value)
        separator = "\n" if "\n" in text else os.pathsep
        items = text.replace(",", separator).split(separator)
    return [item.strip() for item in items if item.strip()]


def source_roots() -> List[str]:
    """Verified extra source roots a native picker may import from.

    Deployment configuration (``project_import_source_roots``), never request
    data: a caller may choose a directory *within* the policy but must not widen
    it. Empty by default, which leaves the member's own projects root as the only
    allowed source.
    """
    return _as_path_list(_conf().get("project_import_source_roots"))


# --- transport 1: loopback + per-start token ---------------------------------


def _env() -> Mapping[str, Any]:
    try:
        import web
        return getattr(web.ctx, "env", None) or {}
    except Exception:  # noqa: BLE001 - outside a request there is no peer
        return {}


def is_loopback_request() -> bool:
    """True only for a genuine local request.

    A forwarding header disqualifies the request even when ``REMOTE_ADDR`` is
    loopback: behind a proxy every request would otherwise look local, and the
    authentication of a *remote* caller would be handed the local path
    privilege.
    """
    env = _env()
    for name in _FORWARDED_HEADERS:
        if str(env.get(name) or "").strip():
            return False
    address = str(env.get("REMOTE_ADDR") or "").strip().lower()
    if not address:
        return False
    if address in _LOOPBACK_ADDRESSES:
        return True
    # ``[::1]``/``::1%lo0`` spellings seen from some clients.
    return address.startswith("::1") or address.startswith("127.")


def _token_file() -> Optional[str]:
    configured = str(_conf().get("local_import_token_file") or "").strip()
    if configured:
        return configured
    try:
        from config import get_data_root
        root = str(get_data_root() or "").strip()
    except Exception:  # noqa: BLE001 - no data root, no published token
        return None
    return os.path.join(root, "local_import.token") if root else None


def local_import_token() -> str:
    """The token a local client must present, generated once per process.

    ``local_import_token`` pins the value when a supervised deployment hands it
    to the client through another channel; otherwise it is random per start and
    published to ``local_import_token_file`` (default
    ``<data_root>/local_import.token``) with mode ``0600``, so the same
    filesystem read permission that lets a client see the file is what proves it
    is local. Publication is best effort: a deployment that cannot write the file
    can still pin the value.

    The file is reconciled on every call, not only when the value is minted: the
    token is the *only* thing proving a request is local, so a missing or stale
    file must not silently outlive the process that owns it -- the local client
    reads this file to learn what to send, and a client that cannot read the
    current token cannot import at all.
    """
    pinned = str(_conf().get("local_import_token") or "").strip()
    if pinned:
        return pinned
    token = _TOKEN_STATE.get("token")
    if not token:
        token = secrets.token_urlsafe(32)
        _TOKEN_STATE["token"] = token
    _publish_token(token)
    return token


def _publish_token(token: str) -> None:
    """Make ``token`` readable by a local client, without rewriting it needlessly.

    An unreadable, unwritable or stale path is reported and ignored: the refusal
    side (``require_local_transport``) is what protects the server, and a
    deployment that hands the token out of band keeps working.
    """
    path = _token_file()
    if not path:
        return
    try:
        with open(path, encoding="utf-8") as handle:
            if handle.read().strip() == token:
                return
    except OSError:
        pass
    try:
        directory = os.path.dirname(path)
        if directory:
            os.makedirs(directory, exist_ok=True)
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(token + "\n")
    except OSError as e:  # noqa: BLE001 - the client can still be given it out of band
        logger.warning("[ProjectImport] cannot publish the local import token: %s", e)


def reset_local_import_token() -> None:
    """Forget the current per-start token (a new process start, or rotation)."""
    _TOKEN_STATE.pop("token", None)


def require_local_transport(params: Mapping[str, Any]) -> None:
    """Require a local transport: loopback *and* the per-start token.

    Called before a request's ``source`` is used for anything. A refusal here
    means no server path was resolved, opened or even stat-ed.
    """
    if not is_loopback_request():
        raise refuse("本机目录导入仅在 loopback 请求上可用，已拒绝",
                     code=CODE_LOCAL_PATH_DENIED, status=403)
    expected = local_import_token()
    supplied = str(params.get("token") or "").strip()
    if not expected or not supplied or not hmac.compare_digest(
            str(expected), str(supplied)):
        raise refuse("本机导入令牌无效，已拒绝", code=CODE_TOKEN_INVALID,
                     status=403)


# --- the single-use handle ---------------------------------------------------


def _purge(now: Optional[float] = None) -> None:
    moment = time.time() if now is None else now
    for token, record in list(_HANDLES.items()):
        if float(record.get("expires_at") or 0) <= moment:
            del _HANDLES[token]


def purge_handles() -> None:
    """Drop expired handles (called on every issue/consume/cancel)."""
    _purge()


def reset_handles() -> None:
    """Forget every handle (test seam; also used when the process restarts)."""
    _HANDLES.clear()


def _binding(identity: Any) -> Tuple[str, str]:
    return (str(getattr(identity, "tenant_id", "") or ""),
            str(getattr(identity, "user_id", "") or ""))


def issue_handle(identity: Any, *, purpose: str, payload: Mapping[str, Any],
                 session_id: Optional[str] = None,
                 ttl: Optional[int] = None) -> str:
    """Issue a single-use handle bound to this member and purpose.

    The binding is the verified identity, not the request: a handle issued to one
    member cannot be redeemed by another, and the recorded source is compared at
    redemption so a handle cannot be replayed for a different directory.
    """
    purge_handles()
    tenant_id, user_id = _binding(identity)
    token = secrets.token_urlsafe(32)
    now = time.time()
    _HANDLES[token] = {
        "handle": token,
        "tenant_id": tenant_id,
        "user_id": user_id,
        "purpose": purpose,
        "session_id": str(session_id or ""),
        "payload": dict(payload or {}),
        "state": "issued",
        "cancelled": False,
        "created_at": now,
        "expires_at": now + float(ttl or HANDLE_TTL_SECONDS),
    }
    return token


def _matches_payload(record: Mapping[str, Any],
                     payload: Optional[Mapping[str, Any]]) -> bool:
    """True when the redemption agrees with what the preview recorded.

    Only the keys the issuer chose to *bind* are compared, so a caller cannot
    "fix" a mismatch by omitting a field. A key whose name starts with ``_`` is
    metadata the import reads but does not have to echo: the chosen target name
    is recorded that way, because the import publishes the name the preview
    showed rather than the one the publishing request happens to carry. The
    grant's identity -- the resolved source -- is always bound and always
    compared.
    """
    recorded = record.get("payload") or {}
    for key, value in recorded.items():
        if key == "digest" or str(key).startswith("_"):
            continue
        if str((payload or {}).get(key, "")) != str(value):
            return False
    return True


def consume_handle(identity: Any, handle: Any, *, purpose: str,
                   session_id: Optional[str] = None,
                   payload: Optional[Mapping[str, Any]] = None) -> Dict[str, Any]:
    """Redeem a handle exactly once, or refuse.

    Refuses (``handle_invalid``) an unknown, expired, already-consumed,
    re-purposed or other-member handle, and a redemption whose source/session no
    longer matches what was previewed. A *cancelled* handle is refused with
    ``cancelled`` (409) so the console can tell "you cancelled it" apart from
    "that capability is not valid".
    """
    purge_handles()
    record = _HANDLES.get(str(handle or ""))
    if record is None:
        raise refuse("导入句柄无效或已过期，已拒绝", code=CODE_HANDLE_INVALID,
                     status=403)
    if str(record.get("purpose") or "") != str(purpose):
        raise refuse("导入句柄用途不匹配，已拒绝", code=CODE_HANDLE_INVALID,
                     status=403)
    if (str(record.get("tenant_id") or ""), str(record.get("user_id") or "")) \
            != _binding(identity):
        raise refuse("导入句柄不属于当前成员，已拒绝", code=CODE_HANDLE_INVALID,
                     status=403)
    if session_id is not None and str(record.get("session_id") or "") != str(
            session_id or ""):
        raise refuse("导入句柄与本次会话不匹配，已拒绝", code=CODE_HANDLE_INVALID,
                     status=403)
    if record.get("cancelled"):
        raise refuse("导入已取消，未发布任何项目", code=CODE_CANCELLED, status=409)
    if str(record.get("state")) != "issued":
        raise refuse("导入句柄已被使用，已拒绝", code=CODE_HANDLE_INVALID,
                     status=403)
    if not _matches_payload(record, payload):
        raise refuse("导入句柄与本次导入的内容不匹配，已拒绝",
                     code=CODE_HANDLE_INVALID, status=403)
    record["state"] = "consumed"
    record["consumed_at"] = time.time()
    return record


def cancel_handle(identity: Any, handle: Any, *, purpose: str) -> bool:
    """Mark a handle cancelled; ``False`` when it is not the caller's.

    A handle stays in the table after it is consumed, so a client that cancels
    *while* the copy is running is still honoured: the import's stage hook reads
    the flag before publishing and rolls back instead (see
    :func:`stage_cancel_check`).
    """
    purge_handles()
    record = _HANDLES.get(str(handle or ""))
    if record is None or str(record.get("purpose") or "") != str(purpose):
        return False
    if (str(record.get("tenant_id") or ""), str(record.get("user_id") or "")) \
            != _binding(identity):
        return False
    record["cancelled"] = True
    return True


def is_cancelled(record: Any) -> bool:
    """Whether the handle behind an in-flight import has been cancelled."""
    return bool(record) and bool(record.get("cancelled"))


def stage_hook(identity: Any, record: Optional[Mapping[str, Any]] = None):
    """The publish-time hook for both transports: honour a cancel, then audit.

    Called by the project-browser module once the copy is complete and before the
    publish -- the last moment at which "cancelled" can still mean "nothing
    happened": the module then removes the staging tree and releases the quota
    reservation. The upload transport passes no handle (there is none), and a
    cancel of an upload is the client abandoning the request.
    """
    from agent.workspace.project_browser import ImportCancelled

    def hook(plan):
        if record is not None and is_cancelled(record):
            raise ImportCancelled("cancelled by the client")
        record_import_event(
            identity, "project.import", str(plan.get("target") or ""),
            "success",
            {"files": plan.get("files"), "dirs": plan.get("dirs"),
             "bytes": plan.get("bytes")})

    return hook


# --- transport 2: the authorized upload -------------------------------------


def upload_params() -> Mapping[str, Any]:
    """The upload transport's form data, with *every* repeated upload kept.

    ``web.rawinput()`` cannot carry this request: its ``dictify`` walks the
    parsed ``MultiDict`` once per key, and ``MultiDict.__getitem__`` returns the
    last value, so a directory upload that sends one ``files`` part per file
    (which is exactly what the console does) is collapsed into a single-file
    request -- and a manifest that lists two paths would then be refused as
    "manifest and file count disagree" even though the request was well formed.

    The parser web.py itself uses is read directly here, so nothing about the
    upload format is re-invented, and the merged storage is stored back on the
    request (``web.ctx._fieldstorage``, web.py's own cache slot) so a later
    ``web.input()`` in the same request sees the same values instead of an empty
    body. The body is therefore parsed at most once, by the same parser.
    """
    try:
        import web
        import multipart
    except Exception:  # noqa: BLE001 - no web.py, no upload transport
        return {}
    cached = getattr(web.ctx, "_project_upload_params", None)
    if cached is not None:
        return cached
    env = dict(getattr(web.ctx, "env", None) or {})
    try:
        forms, files = multipart.parse_form_data(environ=env)
    except Exception as e:  # noqa: BLE001 - a malformed body is refused, not crashed
        raise refuse("上传内容无法解析，已拒绝", code=CODE_INVALID_REQUEST,
                     status=400) from e
    params: Dict[str, Any] = {}
    for key, value in forms.iterallitems():
        params[key] = value
    for key in ("file", "files"):
        parts = files.getall(key)
        if not parts:
            continue
        params[key] = parts[0] if key == "file" else parts
    try:
        web.ctx._fieldstorage = params
        web.ctx._project_upload_params = params
    except Exception:  # noqa: BLE001 - caching is an optimization
        pass
    return params


def _max_upload_bytes(name: str, default: int) -> int:
    return _int_setting(name, default)


def _int_setting(name: str, default: int) -> int:
    """A non-negative integer setting, falling back to ``default``."""
    try:
        return max(0, int(_conf().get(name) if _conf().get(name) is not None
                          else default))
    except (TypeError, ValueError):
        return default


def read_upload_manifest(params: Mapping[str, Any]
                         ) -> Optional[Tuple[Optional[str], List[str],
                                             List[Tuple[str, bytes]]]]:
    """Read a multipart upload into ``(name, paths, entries)``.

    Returns ``None`` when the request carries no uploaded files, so a caller can
    tell "this is not the upload transport" from "this upload is malformed". The
    per-file and total bounds are enforced while reading, so an oversized request
    is refused before the tree is built in memory.
    """
    uploads = params.get("files")
    if uploads is None:
        return None
    if not isinstance(uploads, list):
        uploads = [uploads]
    uploads = [item for item in uploads if item is not None]
    if not uploads:
        return None
    name = str(params.get("name") or "").strip() or None
    raw_paths = params.get("relative_paths") or params.get("paths") or ""
    if isinstance(raw_paths, str):
        text = raw_paths.strip()
        decoded: Any = None
        if text.startswith("["):
            try:
                decoded = json.loads(text)
            except ValueError:
                decoded = None
        paths = [str(item) for item in decoded] if isinstance(decoded, list) \
            else ([text] if text else [])
    elif isinstance(raw_paths, list):
        paths = [str(item) for item in raw_paths]
    else:
        paths = []
    if not paths:
        paths = [str(getattr(item, "filename", "") or "") for item in uploads]
    if len(paths) != len(uploads):
        raise refuse("上传清单与文件数量不一致，已拒绝",
                     code=CODE_INVALID_REQUEST, status=400)

    from channel.web.web_channel import _read_uploaded_file_bytes_limited

    max_file = _max_upload_bytes("project_import_max_file_bytes",
                                 _DEFAULT_MAX_FILE_BYTES)
    max_total = _max_upload_bytes("project_import_max_upload_bytes",
                                  _DEFAULT_MAX_UPLOAD_BYTES)
    entries: List[Tuple[str, bytes]] = []
    total = 0
    for path, item in zip(paths, uploads):
        try:
            data = _read_uploaded_file_bytes_limited(item, max_file)
        except ValueError as e:
            raise refuse("上传文件超过大小上限，已拒绝",
                         code=CODE_UPLOAD_TOO_LARGE, status=413) from e
        total += len(data)
        if total > max_total:
            raise refuse("上传内容超过总大小上限，已拒绝",
                         code=CODE_UPLOAD_TOO_LARGE, status=413)
        entries.append((path, data))
    return name, paths, entries


def preview_upload_request(identity: Any, params: Mapping[str, Any]) -> Dict[str, Any]:
    """Preview the upload transport's manifest through the module."""
    from agent.workspace import project_browser
    manifest = read_upload_manifest(params)
    if manifest is None:
        raise refuse("缺少上传文件，已拒绝", code=CODE_INVALID_REQUEST, status=400)
    name, _paths, entries = manifest
    return project_browser.preview_upload(identity, entries, name=name)


def import_upload_request(identity: Any, params: Mapping[str, Any], *,
                          quota_reserve=None) -> Dict[str, Any]:
    """Publish the upload transport's manifest through the module."""
    from agent.workspace import project_browser
    manifest = read_upload_manifest(params)
    if manifest is None:
        raise refuse("缺少上传文件，已拒绝", code=CODE_INVALID_REQUEST, status=400)
    name, _paths, entries = manifest
    return project_browser.import_upload(
        identity, entries, name=name, quota_reserve=quota_reserve,
        stage_hook=stage_hook(identity))


# --- quota reservation -------------------------------------------------------


def reserve_project_slot(identity: Any, plan: Mapping[str, Any],
                         trusted_root: str):
    """Reserve a project slot before anything is staged (task 6.4).

    The bound is the deployment's project-count limit for a member
    (``project_import_max_projects``, ``0``/absent = unlimited), counted from the
    member's own published projects -- the same count-based shape as the
    scheduler's stored-task limit, because the quantity being bounded is *stored*
    projects and deleting one must free its slot.

    The count and the claim are taken under one lock and in-process reservations
    are counted too, so two imports racing for the last slot resolve to one winner
    and one ``quota_refused``, and the loser has created nothing.
    """
    from agent.workspace import project_browser
    from common import safe_fs

    limit = _int_setting("project_import_max_projects", 0)
    if limit <= 0:
        return _SlotReservation(None)
    with _SLOT_LOCK:
        try:
            names = safe_fs.list_names(trusted_root, None, skip_dotfiles=True)
        except Exception:  # noqa: BLE001 - an unreadable root reserves nothing
            names = []
        used = sum(1 for name in names if safe_fs.is_dir(trusted_root, name))
        if used + _SLOT_STATE["held"] + 1 > limit:
            raise project_browser.ProjectBrowserError(
                "个人项目数量已达上限，未导入任何项目",
                code=project_browser.CODE_QUOTA_REFUSED, status=409)
        _SLOT_STATE["held"] += 1
    return _SlotReservation(limit)


class _SlotReservation:
    """The object the project-browser module commits or releases.

    ``commit`` keeps the slot (the published project is the record) and
    ``release`` returns it, so a rolled-back import does not consume the member's
    allowance. Both are idempotent, because the module releases on failure and
    commits on success and a double call must not corrupt the count.
    """

    def __init__(self, limit: Optional[int]):
        self.limit = limit
        self.state = "reserved"

    def _settle(self, state: str) -> None:
        if self.state == "reserved" and self.limit is not None:
            with _SLOT_LOCK:
                _SLOT_STATE["held"] = max(0, _SLOT_STATE["held"] - 1)
        self.state = state

    def commit(self) -> None:
        self._settle("committed")

    def release(self) -> None:
        self._settle("released")


# --- audit -------------------------------------------------------------------


def record_import_event(identity: Any, action: str, target: str, result: str,
                        changes: Optional[Mapping[str, Any]] = None) -> None:
    """Best-effort business audit for an import attempt.

    The audit is a trace, never an authorization: a failure to record it must not
    change whether the import happened, so it is logged and swallowed. The
    payload goes through the identity service's sanitizer, and it carries counts
    and the chosen name only -- never a source path.
    """
    try:
        from auth.service import get_identity_service
        tenant_id, user_id = _binding(identity)
        get_identity_service().record_business_audit(
            actor_user_id=user_id, tenant_id=tenant_id, action=action,
            target=target, redacted_changes=dict(changes or {}), result=result)
    except Exception as e:  # noqa: BLE001 - a trace must not break the import
        logger.debug("[ProjectImport] audit %s not recorded: %s", action, e)
